### ISSUE TITLE
Include `amp-buildpacks/scarb` in `[order.group]` and dependencies of package

### ISSUE THREAD

**Issue by wangeguo** [amp-buildpacks/cairo#4]
Add new record ([`Scarb`](https://github.com/amp-buildpacks/scarb)) to the following files:
- https://github.com/amp-buildpacks/cairo/blob/main/package.toml
- https://github.com/amp-buildpacks/cairo/blob/main/example-builder.toml#L13
- https://github.com/amp-buildpacks/cairo/blob/main/buildpack.toml#L18

and docs in README:
https://github.com/amp-buildpacks/cairo/tree/main#included-buildpacks

**Comment by zouyuxuan** [comment]
I took it
